# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode10
language: swift
xcode_project: /Users/apple/Desktop/SwiftyGalleryView/Example/SwiftyGalleryView.xcworkspace 
xcode_destination: platform=iOS Simulator,OS=12.1,name=iPhone XR
# cache: cocoapods
# podfile: Example/Podfile
# before_install:
# - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example
script:
- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/SwiftyGalleryView.xcworkspace -scheme SwiftyGalleryView-Example -sdk  ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint --allow-warnings
